apiVersion: v1
kind: Service
metadata:
  name: librespeed
  namespace: final
  labels:
    app.kubernetes.io/instance: librespeed
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: librespeed
    app: librespeed
  ports:
    - port: 80
      targetPort: 80
